name: pfeed
volumes:
  timescaledb_data:
  # minio_data:
services:
  timescaledb:
    image: timescale/timescaledb:2.24.0-pg17
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-pfunder}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    profiles:
      - timescaledb
  # minio:
  #   container_name: pe-minio
  #   image: minio/minio:RELEASE.2025-09-07T16-13-09Z
  #   ports:
  #     - "${MINIO_PORT:-9000}:9000"
  #     - "${MINIO_CONSOLE_PORT:-9001}:9001"
  #   volumes:
  #     - minio_data:/data
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER:-pfunder}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
  #   command: server /data --console-address ":9001"
  #   profiles:
  #     - minio